[package]
name = "advent-of-code-2021"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
lazy_static = "1.4.0"
ndarray = "0.15.3"
rayon = "1.5.1"
regex = "1.5.4"